### ISSUE TITLE
App doesn't work at all after update to 3.12

### ISSUE THREAD

**Issue by Turbotomate** [opendocument-app/OpenDocument.droid#212]
Today i updated the app over F-Droid from v3.10.3 to 3.12. After that i cannot open any document with OpenDocument or even open the app itself. When trying to open a document there is only a completely white screen and the device gets extremely unresposive. When opening the overview of open apps, OpenDocument is not present, so it seems like the app doesn't really start at all.
A restart of the device, stopping the app and deleting its data didn't help.

I have a Samsung Galaxy Note 10+ with stock Android 11.

**Comment by gargamel17** [comment]
Exactly same problem forme me

**Comment by TomTasche** [comment]
Sorry to hear that, but we're not maintaining F-Droid builds ourselves. F-Droid is doing that.

If you report the issue to them, let them know that the issue is probably hidden somewhere here: https://github.com/opendocument-app/OpenDocument.droid/blob/bcf48e2fe55fd0ec7c675b7043d18b7f5d939311/app/src/main/java/at/tomtasche/reader/ui/activity/MainActivity.java#L184-L205

**Comment by Mannshoch** [comment]
Found this ticket here. Because non of the participants had created a ticket on fdroid I did this:
https://gitlab.com/fdroid/fdroiddata/-/issues/2578
Problem now solved. App work after uninstall/reinstall from fdroid.

This app is still a verry nice and helpfull app. Thanks @TomTasche for your work on it.

**Comment by TomTasche** [comment]
Thanks a lot for reporting! :slightly_smiling_face:
